spring.application.name=PlantSam

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB

file.upload-dir=./uploads
file.processed-dir=./processed

server.tomcat.max-swallow-size=100MB